# Course Assessment {.unnumbered}

## Assessment Overview {.unnumbered}

Below you will find the assignment dropboxes for submitting your assignments in this course. Make sure to read the instructions carefully in both your syllabus and below. Additionally, take note of the grading rubrics for your assessments, which provide clear expectations for assignments and insight into how the instructor will evaluate your work.

### Course Evaluation {.unnumbered}

The course grade will be determined by the satisfactory completion of all requirements.

| Assessment | Assesses Course Learning Outcome | Suggested Due Date |
|------------------------------------|------------------|------------------|
| Assignment 1: Reflective Journal (& Assessment Conversation) |  1-4 | End of Unit 3 |
| Assignment 2: Digital Citizenship Blog (& Video Reflection) |  1-7 | End of Unit 5 |
| Assignment 3: Digital Literacy Portfolio (& Assessment Conversation) |  1-7 | End of Unit 6 |

## Assignment Feedback & Grading {.unnumbered}

You will be evaluated in this course based on how well you meet the course learning outcomes, which are equally-weighted. This will involve you completing a series of learning activities and assignments. We will work together to appraise your work on the course assignments in light of the course learning outcomes. You will be required to exercise **evaluative judgment** with respect to how you have met each of the outcomes.

In this course we use a proficiency scale as a gauge to help learners and the instructor ensure that assignments are completed at an appropriate level.

| Not Demonstrated | Emerging | Developing | Proficient | Extending |
|------------------|------------------|------------------|------------------|-------------------|
| The learner does not demonstrate the outcome at a level that is assessable. | The student demonstrates an initial understanding of the concepts and competencies relevant to the expected learning. | The student demonstrates a partial understanding of the concepts and competencies relevant to the expected learning. | The student demonstrates a complete understanding of the concepts and competencies relevant to the expected learning. | The student demonstrates a sophisticated understanding of the concepts and competencies relevant to the expected learning. |

### Grading System {.unnumbered}

At the end of the course, your instructor will summarize all your writing, communicating, collaborating, presenting, reflecting, questioning, evaluating, and learning using one single letter (and maybe a + or –). This grade will be determined by examining your work in relation to the outcomes and through discussions with you.

### University Standard Grading System

| Letter Grade | Grade Description |
|------------------|------------------------------------------------------|
| **A** | **Outstanding, excellent work**; exceptional performance with strong evidence of original thinking, good organization, meticulous concern for documented evidence, and obvious capacity to analyze, synthesize, evaluate, discern, justify, and elaborate; frequent evidence of both verbal eloquence and perceptive insight in written expression; excellent problem-solving ability in scientific or mathematical contexts with virtually no computational errors; demonstrated masterful grasp of subject matter and its implications. Gives evidence of an extensive and detailed knowledge base. (Note: The A+ grade is reserved for very rare students of exceptional intellectual prowess and accomplishment, especially in lower-level courses.)  <br/><br/>**Proficiency Scale: Extending** |
| **B** | **Good, competent work**; laudable performance with evidence of some original thinking, careful organization; satisfactory critical and analytical capacity; reasonably error-free expository written expression, with clear, focused thesis and well-supported, documented, relevant arguments; good problem-solving ability with few computational or conceptual errors in scientific subjects; reasonably good grasp of subject matter but an occasional lack of depth of discernment; evidence of reasonable familiarity with course subject matter in both concepts and key issues. Exhibits a serious, responsible engagement with the course content.<br/><br/>**Proficiency Scale: Proficient** |
| **C** | **Adequate, reasonably satisfactory work**; fair performance but infrequent evidence of original thinking or the capacity to analyze, synthesize, or evaluate course material; undue reliance on rote memory; difficulty in applying knowledge in unfamiliar contexts; limited problem-solving ability in scientific subjects; fairly clear but quite uninspiring written expression with occasional problems in mechanics or syntax; weak in provision of documented, illustrative, or descriptive evidence; satisfactory grasp of basic elements of the course but frequent lapses in detailed understanding. Satisfies the minimum requirements of the course. <br/><br/>**Proficiency Scale: Developing** |
| **D** | **Minimally acceptable work**; relatively weak performance with little evidence of original thinking or ability to analyze or synthesize course material; nominal or weak problem-solving ability in scientific subjects; written expression frequently exhibits difficulty in articulating a central thesis or sustaining a coherent argument; ideas are trite or juvenile without discernible development. Shows inadequate grasp of some basic elements of the course. <br/><br/>**Proficiency Scale: Emerging** |
| **F** | **Inadequate work**; poor performance that indicates a lack of understanding or misunderstanding of essential subject matter; seems easily distracted by the irrelevant; written expression is poorly organized, often incoherent, and rife with mechanical and diction errors. Shows little evidence of even basic competency in the course content or skills. <br/><br/>**Proficiency Scale: Not Demonstrated** |

For more information please see the [University Standard Grading System](https://www.twu.ca/about-us/policies-guidelines/student-policies/university-standard-grading-system){target="_blank"} website.

```{=html}
<!-- ## Assignment Dropboxes {.unnumbered}

Click on the following links for assignment details, including instructions and grading rubrics. When you are ready to submit an assignment, click "Add submission".  For more guidance, refer to the Knowledge Base article [How to Submit an Assignment](https://trinitywestern.teamdynamix.com/TDClient/1904/Portal/KB/ArticleDet?ID=134318){target="_blank"}.

- Assignment 1: Reflective Journal
- Assignment 2: Digital Citizenship Blog
- Assignment 3: Digital Literacy Portfolio -->
```

## Assessment Conversations {.unnumbered}

Course assignments are designed to give you the opportunity to demonstrate your understanding of the course learning outcomes.

Throughout the course you will have several opportunities to elicit feedback from your instructor and/or Global Educational Facilitators. We will work together to appraise your work on the learning activities and assignments in light of the course learning outcomes. You will be required to exercise **evaluative judgment** with respect to how you have met each of the outcomes.

These assessment conversations may be asynchronous (e.g. communicating via chat, email or shared documents), or you may wish to schedule a synchronous meeting with your instructor and/or facilitator via MS Teams or Zoom.

The result of that conversation is that you and your instructor will know

-   How well you performed in relation to the outcomes
-   What you need to do to improve your performance in relation to the outcomes

These conversations are meant to be formative and may not result in a 'grade' on your assignment. You will receive feedback you can use to improve your standing in the course on the next assessment.

## Course Discussions {.unnumbered}

Discussions are an integral part of this course as they provide opportunities for you to engage with the course material, share perspectives, and enhance your understanding through collaborative learning. The discussions are intended to be informal and to facilitate exploration of ideas.

**Expectations:**

-   Discussions are mandatory but ungraded. *You will not be able to complete your final assignment if you do not engage in discussions.*
-   Discussion prompts will be provided in the unit.
-   You are expected to actively participate in discussions throughout the course.

**Ways to Discuss:**

Discussions are not limited to formal online forums. They can take place in informal settings with peers, friends, or coworkers. The emphasis is on active engagement and critical reflection.

-   You may use platforms such as Discourse or other social media platforms.
-   You may use your conversations with friends and coworkers.

**Instructions:**

After working through each unit, refer to the specific discussion questions as posed by your instructor.

-   *Online Discussions*
    -   If discussing through an online chat platform, you may wish to write down your response first in your notes, as you can use this later in your assignments.
    -   Post your response and engage with others. Be sure to take note of others’ insights and feedback to use for your reflection paper.



-   *In Person Discussions:*

    -   If discussing with peers or coworkers, jot down your notes, including any context you may need to provide those you engage in discussion. (e.g., course topics or readings)
    -   Remember to follow ethical guidelines in interactions with those outside of your course:
        -   Let participants know what course you are taking and the purpose of this discussion assignment.
        -   Let participants know that participation is optional, and they can opt out at any time.
        -   Assure them that you will not use any identifiable information in the Reflection Paper.
    -   During or after your conversation, jot down notes on any insights gathered through this academic discourse.

**Why Discuss?**

Taking an active role in discussions will allow you to:

-   Understand the course material more thoroughly by exploring different perspectives.
-   Sharpen your ability to think critically and develop well-reasoned arguments.
-   Learn from your peers, share resources, and build on each other's ideas.
-   Improve your ability to express ideas clearly and respond respectfully.
-   Broaden your perspective and enhance your ability to appreciate different viewpoints.
-   Develop your evaluative judgment by identifying your strengths and areas for improvement.
-   Prepare for future professional challenges by simulating real-world collaboration and problem solving.

By actively participating in discussions you'll not only meet course requirements but also develop skills that will benefit your academic and professional future.

**Other Tips**

-   Take the time to craft your responses with care, ensuring clarity and coherence.
-   Use concepts and resources from the course to back up your viewpoints.
-   Use professional language in your posts to maintain a respectful tone.
-   Engage with others' posts thoughtfully, fostering meaningful discussions.
-   Encourage dialogue by asking questions that prompt critical thinking and reflection.

**Privacy Reminder:**

Confidentiality in discussions, whether online or in person, is essential. Participants often share personal or professional experiences to enrich dialogue. Please share discreetly, use pseudonyms when necessary, and refrain from sharing confidential or proprietary information about others. Remember, discussions are confidential to participants; distributing or verbalizing discussion contents to others is a violation. For questions or concerns, contact your instructor.

## Additional Resources {.unnumbered}

Please see the following links and resources as you prepare for the assessment in this course:

1.  [The Learning Commons Resource Centre](https://learningcommons.twu.ca/){target="_blank"}: See the quick guides and writing resources.
2.  [The Writing Centre](https://www.twu.ca/academics/academic-professional-support/learning-commons/writing-centre){target="_blank"}: Book an appointment to get help with the writing process.