## Summary {.unnumbered}

In this first unit, you have had the opportunity to learn about some of the impacts of "the digital*"* on your life. You have started to build an academic knowledge management workflow, a pivotal skill essential for efficiently organizing, accessing, and leveraging information. Throughout the unit, you've actively engaged with digital tools, shared insights into your personal interactions with digital technology, and begun applying these tools to enhance your academic learning experience. Furthermore, you've developed a personalized understanding of digital literacy and explored how to protect yourself and others in digital and online contexts. As you progress through the course, take a moment to identify the specific literacies you aspire to refine and articulate the concrete steps you intend to take in pursuit of these goals.

::: check
Before you move on to the next unit you may want to check that you are able to:

-   Explore common digital tools used at Trinity Western University
-   Describe your engagement with digital technology
-   Apply digital tools to support learning in an academic environment
-   Explain what digital literacy means to you
-   Examine privacy concerns related to various platforms and tools
-   Describe how to protect yourself and others in the digital environment
-   Identify the literacies you plan to improve and what steps you will take to achieve your goals

<iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=651" width="958" height="549" frameborder="0" allowfullscreen="allowfullscreen" title="Unit 1 Progress Check"></iframe><script src="https://create.twu.ca/h5p/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

:::