## 1.2 Understanding the Digital

Our next topic is an introduction to the idea of "the digital." You may recognize that digital tools are deeply embedded in modern society. It is not uncommon for people of all ages to interact with apps and tools that claim to connect people in conversations or networks, or to perform complex tasks for work, or to control various systems in our vehicles. Digital technology is really everywhere we look. Thinking about these tools is one way to conceptualize how we interact with digital tools but we can also recognize that our social practices and norms have been impacted by digital tools. An example of this, at least in North America, is that the names of companies have become verbs. If people want to learn something about a topic, they *Google* it.

Mobile phones are often essential tools for communication, social media, internet browsing, messaging, entertainment, photography, navigation, online shopping, mobile banking, productivity, two-factor authentication for some websites, and health and fitness management. In some cases, such as in social media, it is almost impossible to participate in public discourse without access to technology.

Modern universities are also deeply impacted by the digital. Every system involved in higher education has been digitized in some manner, including recruitment, accounting, and fundraising. At TWU, here are some digital systems you will likely encounter:

-   Courses are designed and often delivered digitally.
-   Course logistics (discussion forums, assignment submissions, quizzes, gradebooks) happen in large digital tools called learning management systems (LMS) or virtual learning environments (VLE) such as Moodle.
-   Assignments must often be created digitally (using word processors, presentation software, video editors, website builders).
-   Research data is gathered, stored, analyzed, and shared digitally.

There are many other processes and procedures that rely on the digital in higher education, but the important thing for you to realize is that there are many tools that you will be required to learn and use. Some are obvious, such as word processors, presentation software, email, the library website, and the LMS, but others are less obvious and won't necessarily be taught specifically, other than in this course.

Some of the digital tools we will introduce to you will help you build a workflow for you to manage the huge amount of information and resources that you will have to sort through to complete many of your assignments. You will learn to use AI to find relevant resources on whatever your topic might be. As you may know from searching Google, a simple search of the web can turn up thousands or millions of hits, but there are tools that can help you highlight the most relevant resources in just a few clicks.

Once you find resources, we will show you tools that will allow you to track all your references, create citations in your writing quickly and easily, and then create a perfectly formatted reference list. Do not waste your time creating your own bibliographies! This one tool will save you days and likely weeks of work during your degree (quite literally).

We will show you another tool that will allow you to make connections between ideas and notes so that you build a network of connected ideas. Curating this network of ideas is possibly one of the most useful things you can do. You will end up with a searchable network of everything you've learned and be able to visualize it at the click of a button.

Additionally, we’ll guide you through thinking about your digital presence. You’ll learn to make wise decisions about how to present yourself online, what to share, and how to share it. We will also help you make connections on the web that could become a key resource for your learning and working in your career.

As you watch the upcoming video, think about how these digital tools fit into your own learning and professional journey. Which tools resonate most with your goals and aspirations? Consider how you can tailor your focus to build a digital toolkit that not only supports your academic success but also aligns with your long-term professional trajectory.

### 1.2.1 Activity: Reflection on Self-Directed Learning

::: {.learning-activity time="20"}
In the following video, Dr. Timothy Stafford explores the transformative power of heutagogy in education, highlighting how self-driven learning fosters autonomy, discovery, and lifelong growth. With over 30 years of expertise in instructional design, educational technology, and leadership, Dr. Stafford has shaped thousands of online courses across diverse industries. In this TEDx talk, he shares insights from his extensive experience, emphasizing the potential of personalized, future-focused education.

[Watch: *The Future of Education is Self-Directed Learning*](https://www.youtube.com/watch?v=NkmiquiJ_nA){target="_blank"} (2024)

{{< video https://www.youtube-nocookie.com/embed/NkmiquiJ_nA >}}

While you watch the video think about:

-   What is heutagogy?
-   How do you self-determine the value of your learning?
-   What digital skills are important for you to develop?
:::
