## Building a Learning Blog

In the next activity, you will gain firsthand experience in using blog technology to publish your own website. You will "declare" yourself online using your PLE as an alternative to posting an introduction in a closed course forum typically used in a conventional online course. Note that TWU online courses often use either Moodle Discussion Forums or the Learning Community in Discourse to facilitate conversations. By using a platform such as WordPress you can retain the contents of your posts as well as the comments of your peers. In a learning management system (LMS) such as Moodle you may lose access to what you have posted in discussions, and more importantly, conversations with your peers. As you create your personal blog in WordPress (or your own selected blog site), you have more control over your data and who can see it.

You will retain control of your data and learning outputs generated during this online course, even after the course is completed. You get to choose:

- The blog service you would like to use, although **we recommend WordPress as it is supported by TWU**
- Whether to accept comments on your blog from your peers
- Whether to register your blog for the aggregated course feed so that any posts tagged with the course code (LDRS101) will be harvested for the feed

A key teaching philosophy of this course is to embed the acquisition of new digital literacies into your learning journey. Knowledge of how to use the internet and social media technologies will better prepare you for life in a digital world. If this is your first time blogging, you should spend time setting up your personal digital learning environment. Please remember that your learning blog and the social media technologies you use on this course are public, and that you take full responsibility for anything you publish. Do not disclose any confidential information and respect the privacy of others. In short, don’t say anything that you would not want to read on the internet.

### Activity: Setting up Your Learning Blog

### Activity: Blog Challenge!

In this learning activity, you will be asked to create a page, write a blog post, and add multimedia to your blog. Let’s get started!

1. **Edit Your "About" Page**

> Update your personal details on your blog’s "About" page.

1. **Write a Blog Post** Reflect on creating your blog in a new post. Save your work as a draft so you can review before publishing. You might:
    - Introduce yourself and share what you hope to achieve by blogging.
    - Reflect on how easy or challenging you found the setup.
    - Share useful resources you discovered.
    - Offer tips for future learners or note what you’d do differently if starting over.
    - Add anything else your readers might find interesting.
2. **Photo Challenge** Add a photo to your blog post. Use your own image or find one with an open license from sites like [Pixabay](https://pixabay.com/){target="_blank"}, [Unsplash](https://unsplash.com/){target="_blank"}, [Pexels](https://www.pexels.com/){target="_blank"}, [Wikimedia Commons](https://commons.wikimedia.org/){target="_blank"}, or [Flickr](https://www.flickr.com/){target="_blank"}. Make sure you have permission to use the photo. Alternatively, upload your own photo, take a selfie, or ask someone to take a photo of you working on this blog post challenge.
3. **Video Challenge** (Optional) If you’d like, record a short video introduction and embed it in your blog post. You can also share a relevant video you found online. See the resources section for instructions on embedding videos in WordPress.
4. **Publish!**

Review your draft post, and when you’re happy with what you’ve written click "Publish post."

1. **Share your blog**

Add a category or tag for your post using the course tag: LDRS101. Post in the LDRS 101 forum to let your peers know the web address of your blog and ask them to post a comment.

**Additional Resources**

You might find the following resources helpful as you continue building your website:

- *[TWU’s WordPress Support Page](https://servicehub.twu.ca/TDClient/1904/Portal/KB/ArticleDet?ID=146597){target="_blank"}* [@602]
- [*WordPress Support Guides*](https://wordpress.com/support/){target="_blank"} [@602]
- [*Start Here: WordPress Beginner*](https://www.wpbeginner.com/start-here/){target="_blank"} [@606]
- [*WordPress Tutorials; University of Victoria*](https://onlineacademiccommunity.uvic.ca/wordpress-tutorials/){target="_blank"} [@604]
- [*How to Add an Image to a WordPress Website*](https://www.youtube.com/watch?v=W89wPcVU60c){target="_blank"} [@250]
- [How to Add Featured Images in WordPress](https://www.youtube.com/watch?v=9admKGpM3A0){target="_blank"} [@251]
- [https://www.youtube-nocookie.com/embed/9admKGpM3A0](https://www.youtube.com/watch?v=9admKGpM3A0){target="_blank"}

{{< video https://www.youtube-nocookie.com/embed/9admKGpM3A0 >}}

::: {.prote}

Bleep bloop: The above video was auto embedded. If it was just a link, I added a title. If you don't like the title, change it, and I'll leave it alone if I come across it again.

:::

- *[WordPress How to Add Video to a Page or Post](https://www.youtube.com/watch?v=3hCMpnok2Kw){target="_blank"}* [@252] [https://www.youtube-nocookie.com/embed/3hCMpnok2Kw](https://www.youtube.com/watch?v=3hCMpnok2Kw){target="_blank"}

{{< video https://www.youtube-nocookie.com/embed/3hCMpnok2Kw >}}

::: {.prote}

Bleep bloop: The above video was auto embedded. If it was just a link, I added a title. If you don't like the title, change it, and I'll leave it alone if I come across it again.

:::

> If you are confused about anything it is always good to do an initial Google or YouTube search, reach out on Discourse, or email elearning@twu.ca

Congratulations! You created your PLE for TWU!
